pipeline {
    agent any
    
    environment {
        NAME = "public.ecr.aws/r2t7l4m6/capstone3"
        VERSION = "${env.BUILD_ID}-${env.GIT_COMMIT}"
        IMAGE = "${NAME}:${VERSION}"
    }

    stages {
        stage('Checkout Repository - main branch') {
            steps {
                echo 'Checking out code...'
                git branch: 'main', url: 'https://github.com/NickBaynham/capstone3.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building the microservices...'
                sh 'cd application && mvn clean install'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
        stage('Test') {
            steps {
                echo 'Executing the Unit Tests...'
                sh 'cd application && mvn verify'
                junit 'application/target/surefire-reports/*.xml'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the microservices to the cluster...'
                sh 'cd application && docker build . -t $IMAGE'
                sh 'aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws'
                sh 'docker push $IMAGE'
                sh 'cd scripts && ssh ansible@$(./get_node_ip.sh master-node) "kubectl set image deployment microservice microservice=$IMAGE"'
            }
        }
    }
}

