apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/component: microservice
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice
      app.kubernetes.io/component: microservice
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice
        app.kubernetes.io/component: microservice
    spec:
      containers:
      - name: microservice
        image: public.ecr.aws/r2t7l4m6/capstone3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
