- hosts: jenkins

  vars:
          jenkins_version: "2.73.1"
          jenkins_hostname: "jenkins"
          jenkins_port: 80
          jenkins_install_via: "apt"
          jenkins_jobs:
          - "build-test-deploy"
          jenkins-include-secrets: true
          jenkins-plugins:
                  - git
                  - blueocean
  roles:
  - emmetog.jenkins          
