---
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Turn off Swap
    command: swapoff -a 
  - name: Join Worker to the Cluster
    command: "{{ join_command }}"  

