---
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Turn off Swap
    command: sudo swapoff -a
  - name: Set the Hostname to master-node
    command: sudo hostnamectl set-hostname master-node  
  - name: Initialize k8s cluster
    command: sudo kubeadm init --pod-network-cidr=10.244.0.0/16
  - name: Create a directory for the cluster
    file:
      path: /home/ansible/.kube 
      state: directory
      group: ansible
      owner: ansible
      mode: 0700
  - name: Copy the admin config file  
    command: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 
  - name: Change ownership of config  
    command: sudo chown $(id -u):$(id -g) $HOME/.kube/config
  - name: Deploy Pod Network to the Cluster
    command: sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  - name: Verify that everything is running
    command: kubectl get pods --all-namespaces  
